source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.arthurcsh.tech/ios/Pod/Podspecs.git'

use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!
install! 'cocoapods', preserve_pod_file_structure: true

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
